//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by ATSP.RC
//
#define IDR_MAINFRAME                   1
#define IDS_PROVIDERNAME                100
#define IDD_CFGDLG                      101
#define IDS_NORESPONSE                  101
#define IDD_TALKDROP                    102
#define IDS_LINENAME                    102
#define IDC_PORT                        103
#define IDS_ADDRNAME                    103
#define IDC_SPEED                       104
#define IDS_ATTENTION                   104
#define IDC_LINENAME                    105
#define IDS_CR                          105
#define IDC_LINEADDR                    106
#define IDC_INITSTR                     107
#define IDC_IGNORE                      108
#define IDC_ADDRNAME                    108
#define IDC_PULSE                       109
#define IDC_TALK                        110
#define IDC_DROP                        111
#define IDS_PORT                        112
#define IDS_BAUD                        113
#define IDS_PULSE                       114
#define IDS_INITSTR                     115
#define IDS_LINEADDR                    116
#define IDS_NUMLINES                    117
#define IDS_NUMPHONES                   118
#define IDS_OFFHOOK                     119
#define IDS_MODEMINIT                   120
#define IDS_DIAL                        121
#define IDS_MODEMATDT                   122
#define IDS_HANGUP                      123
#define IDS_ERR_INVALIDPORT             124
#define IDS_ERR_INVALIDBAUD             125
#define IDS_ERR_NOLINEADDR              126
#define IDS_PROVIDER                    127
#define IDC_ELAPSEDTIME                 127
#define IDI_PHONE                       127
#define IDS_RESETMOODEM                 128
#define IDC_CALLSTATE                   128
#define IDS_RESETMODEM                  128
#define IDS_ANSWER                      129
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         32767
#define _APS_NEXT_CONTROL_VALUE         129
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
