//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Emulator.rc
//
#define IDR_MAINFRAME                   2
#define IDM_ABOUTBOX                    0x010
#define IDM_NORMAL                      0x020
#define IDM_COMM1                       0x030
#define IDM_COMM2                       0x040
#define IDM_COMM3                       0x050
#define IDM_COMM4                       0x060
#define IDD_ADDRESS_SETUP               102
#define IDD_EMULATOR                    113
#define IDD_ABOUT                       114
#define IDD_CALLNUMBER                  115
#define IDD_DIALDLG                     116
#define IDD_CONFIGURE                   118
#define IDD_DIALGENERATE                119
#define IDB_HOLD                        119
#define IDB_RELEASE                     120
#define IDD_GENERAL_SETUP               120
#define IDB_DIAL                        121
#define IDB_INCOMING                    122
#define IDB_BUSY                        123
#define IDB_ANSWER                      124
#define IDB_GENERATE                    125
#define IDB_EXIT                        126
#define IDB_CONFIG                      127
#define IDB_RESET                       128
#define IDB_LEFT                        129
#define IDB_RIGHT                       130
#define IDB_DIGITS                      131
#define IDD_GENTONE                     132
#define IDB_HELPME                      134
#define IDC_DISPLAY                     1003
#define IDC_MSGWAITING                  1005
#define IDC_LINELIST                    1021
#define IDC_ADDRESS                     1022
#define IDC_NAME                        1023
#define IDC_CESTATUS                    1043
#define IDC_DEBUGINFO                   1044
#define IDC_LAMP0                       1045
#define IDC_LAMP1                       1046
#define IDC_LAMP2                       1047
#define IDC_LAMP3                       1048
#define IDC_LAMP4                       1049
#define IDC_LAMP5                       1050
#define IDC_LAMP6                       1051
#define IDC_LAMP7                       1052
#define IDC_LAMP8                       1053
#define IDC_LAMP9                       1054
#define IDC_LAMP10                      1055
#define IDC_LAMP11                      1056
#define IDC_LAMP12                      1057
#define IDC_LAMP13                      1058
#define IDC_LAMP14                      1059
#define IDC_LAMP15                      1060
#define IDC_SPEAKER                     1062
#define IDC_MICROPHONE                  1063
#define IDC_RESET                       1064
#define IDC_MAKECALL                    1065
#define IDC_HANDSET                     1066
#define IDS_NOSERVER                    1066
#define IDC_BUSY                        1067
#define IDC_ANSWERED                    1068
#define IDC_GENERATE                    1069
#define IDC_BUTTON0                     1070
#define IDS_NOSOCKETS                   1070
#define IDC_BUTTON1                     1071
#define IDC_BUTTON2                     1072
#define IDC_BUTTON3                     1073
#define IDC_BUTTON4                     1074
#define IDC_BUTTON5                     1075
#define IDC_BUTTON6                     1076
#define IDC_BUTTON7                     1077
#define IDC_BUTTON8                     1078
#define IDC_BUTTON9                     1079
#define IDC_BUTTON10                    1080
#define IDC_BUTTON11                    1081
#define IDC_BUTTON12                    1082
#define IDC_BUTTON13                    1083
#define IDC_BUTTON14                    1084
#define IDC_BUTTON15                    1085
#define IDC_HOLD                        1086
#define IDC_RELEASE                     1087
#define IDC_PHONENUMBER                 1088
#define IDC_EXIT                        1088
#define IDC_GENERATETONE                1089
#define IDC_CALLINGNUM                  1091
#define IDC_CALLINGNAME                 1092
#define IDC_INTERNALCALL                1093
#define IDC_STATCALL1                   1094
#define IDC_STATCALL2                   1095
#define IDC_DIAL                        1096
#define IDC_DIALEDIT                    1097
#define IDC_CONFIGURE                   1098
#define IDC_RADIO_CALL                  1100
#define IDC_RADIO_FORWARD               1101
#define IDC_RADIO_TRANSFER              1102
#define IDC_RADIO_DISPLAY               1103
#define IDC_RADIO_BLANK                 1104
#define IDC_STATIC_BTN                  1105
#define IDC_LIST1                       1106
#define IDC_MEDIALIST                   1106
#define IDC_TONELIST                    1106
#define IDC_BTN_CLEAR                   1107
#define IDC_CHECK_PULSE                 1108
#define IDC_BTN_A                       1109
#define IDC_BTN_B                       1110
#define IDC_LIST_FUNCTIONS              1110
#define IDC_BTN_C                       1111
#define IDC_SWINFO                      1111
#define IDC_BTN_D                       1112
#define IDC_VOLDN                       1112
#define IDC_GAINDN                      1113
#define IDC_VOLUP                       1114
#define IDC_GAINUP                      1115
#define IDC_VOLUMEBAR                   1118
#define IDC_GAINBAR                     1119
#define IDC_PREDEFINED                  1119
#define IDC_USERDEFINED                 1120
#define IDC_FREQ1                       1121
#define IDC_FREQ2                       1122
#define IDC_RINGER                      1122
#define IDC_FREQ3                       1123
#define IDW_RINGSOUND1                  1124
#define IDW_RINGSOUND2                  1125
#define IDW_RINGSOUND3                  1126
#define IDC_STAT_INDICATOR              1127
#define IDC_CONTEXT_HELP                1128
#define IDC_TITLE                       1129
#define IDC_EXTERNAL                    1131
#define IDC_DISPLAY2                    6003
#define IDC_MSGWAITING2                 6005
#define IDC_DEBUGINFO2                  6044
#define IDC_SPEAKER2                    6062
#define IDC_MICROPHONE2                 6063
#define IDC_RESET2                      6064
#define IDC_MAKECALL2                   6065
#define IDC_HANDSET2                    6066
#define IDC_BUSY2                       6067
#define IDC_ANSWERED2                   6068
#define IDC_GENERATE2                   6069
#define IDC_HOLD2                       6086
#define IDC_RELEASE2                    6087
#define IDC_EXIT2                       6088
#define IDC_GENERATETONE2               6089
#define IDC_DIAL2                       6096
#define IDC_CONFIGURE2                  6098
#define IDC_VOLUMEBAR2                  6118
#define IDC_GAINBAR2                    6119
#define IDC_RINGER2                     6122
#define IDC_STAT_INDICATOR2             6127

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
