//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by ATV2EXE.RC
//
#define IDS_PORT                        1
#define IDR_MAINFRAME                   2
#define IDS_BAUD                        2
#define IDS_PROVIDER                    3
#define IDS_TITLE                       4

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
