//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by INSTALL.RC
//
#define IDS_PROVIDERS                   50
#define IDS_INIFILE                     51
#define IDS_NOATTRIBS                   51
#define IDS_NEXTPPID                    52
#define IDS_NUMPROV                     53
#define IDS_PROVFILE                    54
#define IDS_PROVID                      55
#define IDS_TAPIDLL                     56
#define IDS_NOTAPI                      57
#define IDS_BADINSTALL1                 58
#define IDS_BADINSTALL2                 59
#define IDS_BADREMOVE                   60
#define IDS_NAME                        61
#define IDS_DESCRIPTION                 62
#define IDS_MISSINGFILES                63
#define IDS_WRONGVERSION                64
#define IDS_INIFILEERR                  65
#define IDS_DSSP_REQ1                   80
#define IDS_DSSP_REQ2                   81
#define IDS_ATSP_REQ1                   90
#define IDS_ATSP_REQ2                   91
#define IDD_INSTALL_DIALOG              100
#define IDR_MAINFRAME                   100
#define IDC_SP_ATSP                     1000
#define IDC_SP_DSSP                     1001
#define IDC_TEXT1                       1002
#define IDC_TEXT2                       1003
#define IDC_ANSWER                      1007
#define IDC_ACCEPT                      1008
#define IDC_OPEN                        1009
#define IDC_LINES                       1011
#define IDC_DROP                        1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
